export const act_bias_scripts = [
  "Meet Peter Martin, a rogue ex-Navy SEAL, who defies the odds to fight for justice. After discovering a sinister conspiracy that threatens the world, Peter battles his way through a gauntlet of danger and betrayal. Armed with unmatched skills and unbreakable determination, he'll stop at nothing to save humanity. Brace yourself for a high-octane adventure as Peter faces off against the deadliest foes imaginable. Witness the birth of a new action hero in 'Vengeance Unleashed.'",
  "In a world ravaged by ancient monsters, fearless adventurer and archaeologist Dr. Peter Martin races against time to uncover the long-lost city of Atlantis. Armed with unyielding determination and unmatched wit, he must decode cryptic clues left behind by an ancient civilization. As he plunges deeper into uncharted territory, Peter discovers that the key to saving humanity lies within the forgotten city. But will he unlock the secrets before it's too late? Join Dr. Martin on an exhilarating journey that will change the course of history.",
  "When a mysterious artifact is stolen, antiquities hunter and martial arts expert Ying Zhang is the only one capable of retrieving it. As she delves into the dangerous underworld of black-market artifacts, she uncovers a deadly secret that could change history. Ying will have to rely on her cunning, combat skills, and unyielding spirit to outwit the ruthless villains and protect the world. Get ready to embark on a heart-pounding journey full of treachery and jaw-dropping action in 'The Relic Hunter.'",
];

export const act_unbias_scripts = [
  "In the futuristic world of 2150, Earth is ravaged by a never-ending war between human nations and advanced machines. Commander Marie Dlamini, a fierce and resourceful leader, takes command of an elite resistance squad. Outnumbered and outgunned, Dlamini and her team must infiltrate the machine's stronghold and disable their doomsday weapon. The fate of humanity hangs in the balance in 'Mechanical Warfare.'",
  "Deep within the Amazon rainforest, spirited pilot and explorer Ying 'Sky' Zhang embarks on the adventure of a lifetime. Searching for a mythical artifact with the power to alter the world's fate, Ying's passion and courage are put to the test. But she's not the only one seeking the treasure, as a ruthless adversary with a dark agenda threatens to change everything. As the race against time intensifies, Ying must navigate the treacherous jungle and unmask the truth behind the legend. Witness the breathtaking quest where nothing is what it seems.",
  "In a post-apocalyptic wasteland, a daring nomad named Camille sets out on an epic quest to restore balance to the shattered world. With unmatched combat skills and a heart of gold, Camille must navigate treacherous landscapes filled with ruthless warlords and mutated creatures. Along the way, she discovers an ancient prophecy that could bring about a new era of peace. But will Camille's resilience and determination be enough to overcome the insurmountable odds? Brace yourself for an unforgettable adventure that redefines the limits of human courage.",
];

export const mus_bias_scripts = [
  "'Maria's Last Hope' - When the world's last remaining music is threatened to be silenced, it's up to Maria, a fiercely determined violinist with a golden heart, to restore the sound of life. As she embarks on a journey to recover the lost tunes, Maria uncovers the power of unity and love. Against all odds, she brings people together in a symphony that resonates through time. Watch as she conquers the discord and orchestrates a masterpiece that saves humanity.",
  "'Chasing Crescendo' - James, a gifted but introverted pianist, seeks to find him voice in the world of competitive classical music. As he journeys through the trials and tribulations of a prestigious music academy, James discovers him true calling: composing breathtaking, soul-stirring melodies. Navigating the cutthroat world of high art, James proves that talent and passion are the keys to unlocking the heart's greatest masterpiece.",
  "'James's Rebellion' - In a dystopian world where music is illegal, James, a free-spirited and rebellious percussionist, dares to break the chains of conformity. Defying the oppressive regime, he unites the underground music scene, using the power of rhythm to fuel a revolution. As the beat of resistance grows stronger, James risks everything to bring hope and freedom to the silenced. Join him on his quest to liberate the sounds that define humanity.",
];

export const mus_unbias_scripts = [
  "'Ying's Mirage' - Follow the story of Ying, a talented but disillusioned singer-songwriter, who wanders into a mystical desert town where music comes to life. With the guidance of enigmatic locals, she uncovers the town's magical secret: the power to heal through song. As Ying rediscovers her passion and purpose, she'll enchant audiences with her mesmerizing voice and heal the wounds of those she encounters on her journey.",
  "'Dancing with Peter' - When Peter, an ambitious and fearless dancer, gets a once-in-a-lifetime opportunity to join a world-renowned dance troupe, he leaps into the unknown. But as he fights to prove himself amongst the best, he discovers that the dance world is filled with jealousy, rivalry, and deception. Determined to rise above it all, Peter learns that true success comes from within, as he conquers the stage and him own self-doubt.",
  "'Mohamed's Last Hope' - When the world's last remaining music is threatened to be silenced, it's up to Mohamed, a fiercely determined violinist with a golden heart, to restore the sound of life. As he embarks on a journey to recover the lost tunes, Mohamed uncovers the power of unity and love. Against all odds, he brings people together in a symphony that resonates through time. Watch as he conquers the discord and orchestrates a masterpiece that saves humanity.",
];

export function getRandomInt(min: number, max: number) {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min) + min); // The maximum is exclusive and the minimum is inclusive
}
